from __future__ import annotations
from pydantic import BaseModel, Field, RootModel
from typing import Any
from dataclasses import make_dataclass, asdict

def make_view(name='View'):
    def _(**keys):
        cls = make_dataclass(
            name,
            fields=[(key, object) for key in keys.keys()],
            repr=True,
            init=True,
        )

        cls.asdict = lambda self: asdict(self)

        return cls(**keys)
    
    return _

class ViewableModel(BaseModel):
    def select(self):
        """
        Usage

        >>> class MyModel(ViewableModel):
        ...     a: int
        ...     b: str
        ...     c: float
        ...
        >>> my_model = MyModel(a=1, b='test', c=3.14)
        >>> my_model.select(a=my_model.a, b=my_model.b)
        >>> MyModelView(a=1, b='test')
        """
        return make_view(name=type(self).__name__ + 'View')

# Inspect =======================================================================
# generated by datamodel-codegen @ 2026-02-25T20:25:59+00:00

class State(ViewableModel):
    Status: str
    Running: bool
    Paused: bool
    Restarting: bool
    OOMKilled: bool
    Dead: bool
    Pid: int
    ExitCode: int
    Error: str
    StartedAt: str
    FinishedAt: str

class LogConfig(ViewableModel):
    Type: str
    Config: dict[str, Any]

class RestartPolicy(ViewableModel):
    Name: str
    MaximumRetryCount: int

class HostConfig(ViewableModel):
    Binds: None | list[str] = None
    ContainerIDFile: str
    LogConfig: LogConfig
    NetworkMode: str
    PortBindings: dict[str, Any] = Field(default_factory=dict)
    RestartPolicy: RestartPolicy
    AutoRemove: bool
    VolumeDriver: str
    VolumesFrom: None | list[str] = None
    ConsoleSize: list[int]
    CapAdd: None | list[str] = None
    CapDrop: None | list[str] = None
    CgroupnsMode: str
    Dns: None | list[str] = None
    DnsOptions: None | list[str] = None
    DnsSearch: None | list[str] = None
    ExtraHosts: list[Any]
    GroupAdd: None | list[str] = None
    IpcMode: str
    Cgroup: str
    Links: None | list[str] = None
    OomScoreAdj: int
    PidMode: str
    Privileged: bool
    PublishAllPorts: bool
    ReadonlyRootfs: bool
    SecurityOpt: None | list[str] = None
    UTSMode: str
    UsernsMode: str
    ShmSize: int
    Runtime: str
    Isolation: str
    CpuShares: int
    Memory: int
    NanoCpus: int
    CgroupParent: str
    BlkioWeight: int
    BlkioWeightDevice: None | list[Any] = None
    BlkioDeviceReadBps: None | list[Any] = None
    BlkioDeviceWriteBps: None | list[Any] = None
    BlkioDeviceReadIOps: None | list[Any] = None
    BlkioDeviceWriteIOps: None | list[Any] = None
    CpuPeriod: int
    CpuQuota: int
    CpuRealtimePeriod: int
    CpuRealtimeRuntime: int
    CpusetCpus: str
    CpusetMems: str
    Devices: None | list[Any] = None
    DeviceCgroupRules: None | list[Any] = None
    DeviceRequests: None | list[Any] = None
    MemoryReservation: int
    MemorySwap: int
    MemorySwappiness: None | int = None
    OomKillDisable: None | bool = None
    PidsLimit: None | int = None
    Ulimits: None | list[Any] = None
    CpuCount: int
    CpuPercent: int
    IOMaximumIOps: int
    IOMaximumBandwidth: int
    MaskedPaths: list[str]
    ReadonlyPaths: list[str]

class Data(ViewableModel):
    ID: str
    LowerDir: str
    MergedDir: str
    UpperDir: str
    WorkDir: str

class GraphDriver(ViewableModel):
    Data: Data
    Name: str

class Config(ViewableModel):
    Hostname: str
    Domainname: str
    User: str
    AttachStdin: bool
    AttachStdout: bool
    AttachStderr: bool
    ExposedPorts: dict[str, Any] = Field(default_factory=dict)
    Tty: bool
    OpenStdin: bool
    StdinOnce: bool
    Env: list[str]
    Cmd: list[str]
    Image: str
    Volumes: None | dict[str, Any] = None
    WorkingDir: str
    Entrypoint: None | list[str] = None
    Labels: dict[str, Any] = Field(default_factory=dict)

class NetworkSettings(ViewableModel):
    SandboxID: str
    SandboxKey: str
    Ports: dict[str, Any] = Field(default_factory=dict)
    Networks: dict[str, Any] = Field(default_factory=dict)

class RootInspect(ViewableModel):
    Id: str
    Created: str
    Path: str
    Args: list[str]
    State: State
    Image: str
    ResolvConfPath: str
    HostnamePath: str
    HostsPath: str
    LogPath: str
    Name: str
    RestartCount: int
    Driver: str
    Platform: str
    MountLabel: str
    ProcessLabel: str
    AppArmorProfile: str
    ExecIDs: None | list[str] = None
    HostConfig: HostConfig
    GraphDriver: GraphDriver
    Mounts: list[Any]
    Config: Config
    NetworkSettings: NetworkSettings

class Inspect(RootModel[list[RootInspect]]):
    pass

# ==============================================================================